// Generated by CoffeeScript 1.10.0

/**
 * Module dependencies.
 */

(function() {
  var Strategy, exports;

  Strategy = require('./strategy');


  /**
   * Expose `Strategy` directly from package.
   */

  exports = module.exports = Strategy;


  /**
   * Export constructors.
   */

  exports.Strategy = Strategy;

}).call(this);
