// Generated by CoffeeScript 1.10.0

/**
 * Parse profile.
 *
 * @param {Object|String} json
 * @return {Object}
 * @api private
 */

(function() {
  exports.parse = function(json) {
    var profile;
    if ('string' === typeof json) {
      json = JSON.parse(json);
    }
    profile = {};
    profile.id = json._id;
    profile.displayName = json.name;
    profile.username = json.name;
    profile.email = json.email;
    profile.emails = json.emails;
    return profile;
  };

}).call(this);
